runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*  # This regex directs all routes to main.app
  script: notify.app

libraries:
- name: ssl
  version: latest

- name: MySQLdb
  version: latest